In [6]:
from random import randint
import numpy as np

In [2]:
"""
Maximizing top-left quadrant
"""

def yeet(n: int):
    matrix = np.random.randint(low=0, high=99, size=(2*n, 2*n))

    print("initial matrix:\n", matrix)
    def horizontal_flip(i: int) -> None:
        matrix[i] = matrix[i][::-1]

    def vertical_flip(j: int) -> None:
        for i in range(n):
            matrix[i][j], matrix[-(i+1)][j] = matrix[-(i+1)][j], matrix[i][j]

    for i in range(n):
        for j in range(n):
            # top right quadrant
            if matrix[i][j] < matrix[i][-(j+1)]:
                for k in range(n):
                    if k != j:
                        vertical_flip(k)
                horizontal_flip(i)
                for k in range(n):
                    if k != j:
                        vertical_flip(k)
            # bottom left quadrant
            if matrix[i][j] < matrix[-(i+1)][j]:
                for k in range(n):
                    if k != i:
                        horizontal_flip(k)
                vertical_flip(j)
                for k in range(n):
                    if k != i:
                        horizontal_flip(k)
            # bottom right quadrant
            if matrix[i][j] < matrix[-(i+1)][-(j+1)]:
                vertical_flip(j)
                horizontal_flip(-(i+1))
                vertical_flip(j)
                horizontal_flip(-(i+1))
    print("final matrix:\n", matrix)
    sum = 0
    for i in range(n):
        for j in range(n):
            sum += matrix[i][j]
    return sum
            
print(yeet(3))

initial matrix:
 [[35 25 30 76 71 52]
 [80 96 52 79 35 54]
 [91 14 87 87 95 17]
 [64 36 82 69 97  8]
 [23 89 58 97  6 20]
 [91 10 81 75 32  5]]
final matrix:
 [[91 71 81 30 10 52]
 [80 96 97 52 89 54]
 [91 97 87 82 14 17]
 [64 95 87 69 36  8]
 [23 35 79 58  6 20]
 [35 25 76 75 32  5]]
791


In [27]:
"""
Insertion Sort (increasing)
"""
def insertion_sort(sequence: list) -> list:
    print("Initial sequence:\n", sequence)
    # do work
    for i in range(1, len(sequence)):
        key = sequence[i]
        j = i - 1
        while j >= 0 and sequence[j] > key:
            sequence[j+1] = sequence[j]
            j -= 1
        sequence[j+1] = key
    return print("Final sequence:\n", sequence)

insertion_sort([randint(0, 100) for _ in range(10)])

Initial sequence:
 [14, 30, 47, 21, 53, 77, 72, 25, 76, 62]
Final sequence:
 [14, 21, 25, 30, 47, 53, 62, 72, 76, 77]


In [69]:
"""
Insertion Sort (decreasing)
"""
def insertion_sort(sequence: list) -> list:
    print("Initial sequence:\n", sequence)
    # do work
    for i in range(1, len(sequence)):
        key = sequence[i]
        j = i - 1
        while j >= 0 and sequence[j] < key:
            sequence[j+1] = sequence[j]
            j -= 1
        sequence[j+1] = key
    return print("Final sequence:\n", sequence)

insertion_sort([randint(0, 100) for _ in range(10)])

Initial sequence:
 [79, 73, 88, 3, 34, 41, 55, 62, 14, 100]
Final sequence:
 [100, 88, 79, 73, 62, 55, 41, 34, 14, 3]
