In [56]:
import numpy as np



def yeet(n: int):
    matrix = np.random.randint(low=0, high=99, size=(2*n, 2*n))

    print("initial matrix:\n", matrix)
    def horizontal_flip(i: int) -> None:
        matrix[i] = matrix[i][::-1]

    def vertical_flip(j: int) -> None:
        for i in range(n):
            matrix[i][j], matrix[-(i+1)][j] = matrix[-(i+1)][j], matrix[i][j]

    for i in range(n):
        for j in range(n):
            # top right quadrant
            if matrix[i][j] < matrix[i][-(j+1)]:
                for k in range(n):
                    if k != j:
                        vertical_flip(k)
                horizontal_flip(i)
                for k in range(n):
                    if k != j:
                        vertical_flip(k)
            # bottom left quadrant
            if matrix[i][j] < matrix[-(i+1)][j]:
                for k in range(n):
                    if k != i:
                        horizontal_flip(k)
                vertical_flip(j)
                for k in range(n):
                    if k != i:
                        horizontal_flip(k)
            # bottom right quadrant
            if matrix[i][j] < matrix[-(i+1)][-(j+1)]:
                vertical_flip(j)
                horizontal_flip(-(i+1))
                vertical_flip(j)
                horizontal_flip(-(i+1))
    print("final matrix:\n", matrix)
    sum = 0
    for i in range(n):
        for j in range(n):
            sum += matrix[i][j]
    return sum
            
print(yeet(3))

initial matrix:
 [[18 11 83 80 66 13]
 [35 15  9 28  6 86]
 [14 71 96 34 65 26]
 [62  6 58  1 49  6]
 [49 82 46 49 11 31]
 [12 52 66 56 78 49]]
final matrix:
 [[49 78 83 80 11 13]
 [86 82 49  9  6 49]
 [62 71 96 34  6 14]
 [26 65 58  1 49  6]
 [35 15 46 28 11 31]
 [18 66 66 56 52 12]]
656
